// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCphJVw6rrxzuf82nzD4sBuNH7t6zK5VoA',
    appId: '1:467606789977:web:a0b7c2073d6fcfbccf7648',
    messagingSenderId: '467606789977',
    projectId: 'deploy-1a168',
    authDomain: 'deploy-1a168.firebaseapp.com',
    storageBucket: 'deploy-1a168.appspot.com',
    measurementId: 'G-55EZJ1KV0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB26Hrg9cEAyqjumVImXuRI8wdI72_YrnQ',
    appId: '1:467606789977:android:e4970f2cde7eb4cdcf7648',
    messagingSenderId: '467606789977',
    projectId: 'deploy-1a168',
    storageBucket: 'deploy-1a168.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEz580kAtoL05TkHumJvQYq7cP67Xl7Zc',
    appId: '1:467606789977:ios:21cd0d5b6568e29ecf7648',
    messagingSenderId: '467606789977',
    projectId: 'deploy-1a168',
    storageBucket: 'deploy-1a168.appspot.com',
    iosBundleId: 'com.example.demoCicd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEz580kAtoL05TkHumJvQYq7cP67Xl7Zc',
    appId: '1:467606789977:ios:21cd0d5b6568e29ecf7648',
    messagingSenderId: '467606789977',
    projectId: 'deploy-1a168',
    storageBucket: 'deploy-1a168.appspot.com',
    iosBundleId: 'com.example.demoCicd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCphJVw6rrxzuf82nzD4sBuNH7t6zK5VoA',
    appId: '1:467606789977:web:0519798cde25447ccf7648',
    messagingSenderId: '467606789977',
    projectId: 'deploy-1a168',
    authDomain: 'deploy-1a168.firebaseapp.com',
    storageBucket: 'deploy-1a168.appspot.com',
    measurementId: 'G-654487QNB4',
  );
}
