#name: Build and Release Android
#on:
#  push:
#    branch:
#      - main
#jobs:
#  build:
#    name: Build Android
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v2
#        with:
#          distribution: 'zulu'
#          java-version: '11'
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.22.0'
#      - run: flutter pub get
#      - run: flutter build apk
#      - name: Push APK to Releases
#        uses: wzieba/Firebase_Distribution-Gidhub-Action@v1.3.3
#        with:
##          appId: ${{secrets.APPID}}
#          appId: "1:127101180798:android:a2b0c735c2db444183712f"
##          token: ${{secrets.TOKEN}}
#          token: "1//0eMlILV7Xf_WOCgYIARAAGA4SNwF-L9IrjYYOyInoGgDWHcEZLB_ogJcX-qtNwi467BkpHTgvyp4efzcItNmVKb71udpCQU7N6es"
#          groups: testers
#          file: build/app/outputs/flutter-apk/app-release.apk
