name: Build and Release Android
on:
  push:
    branch:
      - main
jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - run: flutter pub get
      - run: flutter build apk
      - name: Push APK to Releases
        uses: wzieba/Firebase_Distribution-Gidhub-Action@v1.3.3
        with:
#          appId: ${{secrets.APPID}}
          appId: "1:467606789977:android:e4970f2cde7eb4cdcf7648"
#          token: ${{secrets.TOKEN}}
          token: "1//0ed_AItGokZtmCgYIARAAGA4SNwF-L9Ireb1NXoUxuQ8Mttsgv7Kcg_0BA9ow8qU-B9M3I2bN3BY6_xYC-RerIlXMOOq5HylqAVk"
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
